### PR TITLE
Authnrequest subject support processing feedback

### PR DESCRIPTION
**Pull request by DRvanR**

### CODE REVIEW

**Comment by relaxnow** [comment]
lookin good!

Only missing the tests.
I'm such a hypocrite

**Comment by DRvanR** [comment]
I'm running into issues while writing the EncryptedNameID test. Using the following code:
```php
        $rawNameId = md5('Arthur Dent');

        $request = new SAML2_AuthnRequest();
        $request->setIssuer('https://gateway.stepup.org/saml20/sp/metadata');
        $request->setDestination('https://tiqr.stepup.org/idp/profile/saml2/Redirect/SSO');
        $request->setNameId(array('Value' => $rawNameId, 'Format' => SAML2_Const::NAMEID_ENCRYPTED));

        $key = SAML2_CertificatesMock::getPublicKey();

        $request->encryptNameId($key);
```

I get the following AuthnRequest:
```xml
<samlp:AuthnRequest
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
    ID="123"
    Version="2.0"
    IssueInstant="2015-05-08T12:23:33Z"
    Destination="https://tiqr.stepup.org/idp/profile/saml2/Redirect/SSO">
    <saml:Issuer>https://gateway.stepup.org/saml20/sp/metadata</saml:Issuer>
    <saml:Subject>
        <saml:EncryptedID>
            <xenc:EncryptedData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" xmlns:dsig="http://www.w3.org/2000/09/xmldsig#" Type="http://www.w3.org/2001/04/xmlenc#Element">
                <xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/>
                <dsig:KeyInfo xmlns:dsig="http://www.w3.org/2000/09/xmldsig#">
                    <xenc:EncryptedKey>
                        <xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-1_5"/>
                        <xenc:CipherData>
                            <xenc:CipherValue>PgdkcUYgPl1SoUQarwiDbAUUAg/w0nnKKmKIEtu+p09VD7NRji+Rmf2BReXHHcYP+0fWs8dzl65HGwP04BEHLeNu8KkqqX62b6G3v9OrdvA0vctWhtkNjb9krboI1EHAJZ52aKbmk4LKFYVVnQjQuAqRnAcYUzs4NcmNZ+IM8Yw=</xenc:CipherValue>
                        </xenc:CipherData>
                    </xenc:EncryptedKey>
                </dsig:KeyInfo>
                <xenc:CipherData>
                    <xenc:CipherValue>MICuV9eeHMEljHrP6+qpcizVhuVb2c7/te2yBvHvkaEvsgtiIuFd2Mh4lYhhLE8VBFmthpFRon9qks5iw0O0o+yd+ODmnNnOkDx0vx6dj2KYkRHb9POpNW9HnRlhVp1GZKoUsQUjy3Mx66wUqmq+ei0V+EZmgeAuMEgbwgJPJIs=</xenc:CipherValue>
                </xenc:CipherData>
            </xenc:EncryptedData>
        </saml:EncryptedID>
    </saml:Subject>
</samlp:AuthnRequest>
```

When decrypting that, using the following code:
```php
        $document = new DOMDocument();
        $document->loadXML('*** the authnrequest above ***');

        $key = SAML2_CertificatesMock::getPublicKey();

        $req = new SAML2_AuthnRequest($document->documentElement);

        $req->decryptNameId($key);
```

I get the following exception: `Failed to decrypt XML element.` throw [here][1]. Tracing the exception leads to the [original exception][2], which is throw because the encrypted element is not found. When debugging this, I found that the [decrypted value][3] was empty.

According to [the spec][4] the xml is correct. The encryption and decryption was directly copied from the [Assertion][5], not sure how to proceed now.

@relaxnow: any thoughts on this (seeing you've got a bit more experience regarding this lib ;) )? Or maybe you can point me to someone who can shed a light on this?

[1]: https://github.com/SURFnet/saml2/blob/feature/authnrequest-subject-support/src/SAML2/Utils.php#L533
[2]: https://github.com/SURFnet/saml2/blob/1078dfa92bd8fe911863b9c8ac0a33c1383d0e74/src/SAML2/Utils.php#L504
[3]: https://github.com/SURFnet/saml2/blob/1078dfa92bd8fe911863b9c8ac0a33c1383d0e74/src/SAML2/Utils.php#L487
[4]: https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf
[5]: https://github.com/SURFnet/saml2/blob/1078dfa92bd8fe911863b9c8ac0a33c1383d0e74/src/SAML2/Assertion.php#L670-L715

**Comment by DRvanR** [comment]
@relaxnow Any other requests? :wink:

**Comment by relaxnow** [comment]
Yeah, could you refactor everything? :wink: 
:+1: from me.

**Pull request merged**
